variables:

  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS: "6514223"

before_script:
  - echo "sdk.dir=${ANDROID_HOME}" >> local.properties
  - echo "ndk.dir=${ANDROID_NDK_HOME}" >> local.properties
  - chmod +x ./gradlew
  - export FIREBASE_TOKEN=1//0eFo0ughP5DHoCgYIARAAGA4SNwF-L9IrLGxik_P7gzRKrqk2eWqegoo0sxjtEZL1Y5AaYW_KYavsE2CJySv2aQb3Gl_KBOOTKy4

stages:
  - deploy
  - publish

deployDevelop:
  only:
    - /^1.9.\d+$/
  stage: deploy
  script:
    - ./gradlew assembleDevelopmentDebug appDistributionUploadDevelopmentDebug
  artifacts:
    paths:
      - nunchuk-app/build/outputs/

uatDevelop:
  only:
    refs:
      - main
  stage: deploy
  script:
    - ./gradlew assembleDevelopmentDebug appDistributionUploadDevelopmentDebug
  artifacts:
    paths:
      - nunchuk-app/build/outputs/

publishProduction:
  stage: publish
  only:
    refs:
      - main
  script:
    - ./gradlew bundleProductionRelease appDistributionUploadProductionRelease --artifactType="AAB"


#Create checksum file: sha256sum * > SHA256SUMS
#Sign the checksum file: gpg --clearsign SHA256SUMS
#Attach the newly created file SHA256SUMS.asc to Github release