variables:

  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS: "6514223"

before_script:
  - echo "sdk.dir=${ANDROID_HOME}" >> local.properties
  - echo "ndk.dir=${ANDROID_NDK_HOME}" >> local.properties
  - chmod +x ./gradlew
  - export FIREBASE_TOKEN=1//0eFo0ughP5DHoCgYIARAAGA4SNwF-L9IrLGxik_P7gzRKrqk2eWqegoo0sxjtEZL1Y5AaYW_KYavsE2CJySv2aQb3Gl_KBOOTKy4

stages:
  - build
  - lint
  - test
  - deploy
  - publish

buildDevelopment:
  stage: build
  script:
    - ./gradlew assembleDevelopmentDebug

lintDevelopment:
  stage: lint
  script:
    - ./gradlew lintDevelopmentDebug

testDevelopment:
  stage: test
  script:
    - ./gradlew testDevelopmentDebug

deployDevelop:
  only:
    - /^sandbox.android.v\d+.\d+.\d+$/
  stage: deploy
  script:
    - ./gradlew assembleDevelopmentDebug appDistributionUploadDevelopmentDebug
  artifacts:
    paths:
      - nunchuk-app/build/outputs/

uatDevelop:
  only:
    - /^release.android.v\d+.\d+.\d+$/
  stage: deploy
  script:
    - ./gradlew assembleDevelopmentDebug appDistributionUploadDevelopmentDebug
  artifacts:
    paths:
      - nunchuk-app/build/outputs/

publishProduction:
  stage: publish
  only:
    - /^android.\d+.\d+.\d+$/
  script:
    - ./gradlew bundleProductionRelease appDistributionUploadProductionRelease -PappDistribution-artifactType="AAB"
